[package]
name = "proyecto2"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.8"
lazy_static = "1.5.0"
raylib = "5.5.1"
rayon = "1.11.0"
tobj = "4.0.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
